version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - budget-app-network
    volumes:
      - $HOME/$USER/database/mongo/data:/datadb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root  

  mongoexpress:
    container_name: mongoexpress
    image: mongo-express
    ports:
      - "8080:8081"
    networks:
      - budget-app-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      #ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:root@172.27.130.36:27017/DB

  
networks:
  budget-app-network:
    driver: bridge
