name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js v20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: "v20.11.1"
          cache: "npm"

      - name: Run lint
        run: npx prettier . --check

      - name: Run Prettier fix
        run: npx prettier . --write
        if: failure()

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js v20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: "v20.11.1"
          cache: "npm"

      - name: Install dependencies
        working-directory: .
        run: npm install

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Start MongoDB Memory Server
        working-directory: ./backend
        run: npm install mongodb-memory-server

      - name: Run tests
        working-directory: ./backend
        run: npm test
