name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Debug working directory
      run: pwd
      working-directory: ./backend

    - name: List contents of backend directory
      run: ls -alh
      working-directory: ./backend

    - name: Install dependencies for backend
      run: npm install
      working-directory: ./backend

    - name: Run tests for backend
      run: npm test
      working-directory: ./backend
