name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'v20.11.1'

    - name: Install all dependcies
      run: npm install
      working-directory: ./backend

    - name: Run tests
      run: npm test
      working-directory: ./backend # this should run test in backend thats why it was failing in github
